// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEYUrbcKvv35h9T5vVGQ7CGTArNtiFysA',
    appId: '1:841732223002:web:3a593582ec8d306d2a21a3',
    messagingSenderId: '841732223002',
    projectId: 'dalel-de9cf',
    authDomain: 'dalel-de9cf.firebaseapp.com',
    storageBucket: 'dalel-de9cf.appspot.com',
    measurementId: 'G-SLRY61S2HT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmWS27-oFXfk1EhYEmGpLkcERElPsiGcA',
    appId: '1:841732223002:android:dd4f3d9a3dc288012a21a3',
    messagingSenderId: '841732223002',
    projectId: 'dalel-de9cf',
    storageBucket: 'dalel-de9cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxNRA-zr5hUncFcRUkb-ncIMNWr8gUujE',
    appId: '1:841732223002:ios:3d0d97fa56c6d1e42a21a3',
    messagingSenderId: '841732223002',
    projectId: 'dalel-de9cf',
    storageBucket: 'dalel-de9cf.appspot.com',
    iosBundleId: 'com.example.dalel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxNRA-zr5hUncFcRUkb-ncIMNWr8gUujE',
    appId: '1:841732223002:ios:b517a06697598a442a21a3',
    messagingSenderId: '841732223002',
    projectId: 'dalel-de9cf',
    storageBucket: 'dalel-de9cf.appspot.com',
    iosBundleId: 'com.example.dalel.RunnerTests',
  );
}
